=== Ysoap/komidabot-docker/tests/external_menus/raw.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "optional_string": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    }
  },
  "title": "ExternalMenu",
  "type": "object",
  "properties": {
    "$schema": true,
    "id": {
      "type": "integer"
    },
    "menuDate": {
      "type": "string",
      "format": "date-time"
    },
    "restaurantId": {
      "type": "integer"
    },
    "chefId": {
      "type": "integer",
      "minimum": 0,
      "maximum": 0
    },
    "description": {
      "type": "null"
    },
    "approvedById": {
      "type": "integer",
      "minimum": 0,
      "maximum": 0
    },
    "approvedDateTime": {
      "type": "string",
      "format": "date-time"
    },
    "approved": {
      "type": "boolean",
      "enum": [
        false
      ]
    },
    "requestToBeApproved": {
      "type": "boolean",
      "enum": [
        false
      ]
    },
    "remark": {
      "type": "null"
    },
    "menuItems": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "nameNl": {
            "type": "null"
          },
          "nameEn": {
            "type": "null"
          },
          "menuTypeId": {
            "type": "integer",
            "minimum": 0,
            "maximum": 0
          },
          "chefId": {
            "type": "integer",
            "minimum": 0,
            "maximum": 0
          },
          "enabled": {
            "type": "integer",
            "minimum": 0,
            "maximum": 2
          },
          "remark": {
            "type": "null"
          },
          "menuid": {
            "type": "integer"
          },
          "sortorder": {
            "type": "integer",
            "minimum": 0,
            "maximum": 11
          },
          "menuItemContents": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "menuItemId": {
                  "type": "integer"
                },
                "courseId": {
                  "type": "integer"
                },
                "sortOrder": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 0
                },
                "course": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "dispNameNl": {
                      "type": "string"
                    },
                    "dispNameEn": {
                      "type": "string"
                    },
                    "nameNl": {
                      "type": "string"
                    },
                    "nameEn": {
                      "type": "string"
                    },
                    "weight": {
                      "$ref": "#/definitions/optional_string"
                    },
                    "extra": {
                      "$ref": "#/definitions/optional_string"
                    },
                    "preparation": {
                      "$ref": "#/definitions/optional_string"
                    },
                    "price": {
                      "type": "number",
                      "minimum": 0.0
                    },
                    "photo": {
                      "type": "string",
                      "enum": [
                        ""
                      ]
                    },
                    "isCourse": {
                      "type": "boolean"
                    },
                    "isIngredient": {
                      "type": "boolean"
                    },
                    "course_CategoryForCourses": {
                      "type": "null"
                    },
                    "course_Allergens": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "courseId": {
                            "type": "integer"
                          },
                          "allergenId": {
                            "type": "integer"
                          }
                        },
                        "required": [
                          "courseId",
                          "allergenId"
                        ],
                        "additionalProperties": false
                      }
                    },
                    "course_CourseLogos": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "courseId": {
                            "type": "integer"
                          },
                          "courseLogoId": {
                            "type": "integer"
                          }
                        },
                        "required": [
                          "courseId",
                          "courseLogoId"
                        ],
                        "additionalProperties": false
                      }
                    },
                    "maincourse": {
                      "type": "boolean"
                    },
                    "menuInfo": {
                      "$ref": "#/definitions/optional_string"
                    },
                    "fixedMultiplePrices": {
                      "type": "boolean"
                    },
                    "calculatedMultiplePrices": {
                      "type": "boolean"
                    },
                    "fixedprice": {
                      "type": "boolean"
                    },
                    "showFirst": {
                      "type": "boolean"
                    },
                    "deleted": {
                      "type": "boolean"
                    },
                    "enabled": {
                      "type": "boolean"
                    },
                    "menuInfoEn": {
                      "$ref": "#/definitions/optional_string"
                    }
                  },
                  "required": [
                    "id",
                    "dispNameNl",
                    "dispNameEn",
                    "nameNl",
                    "nameEn",
                    "weight",
                    "extra",
                    "preparation",
                    "price",
                    "photo",
                    "isCourse",
                    "isIngredient",
                    "course_CategoryForCourses",
                    "course_Allergens",
                    "course_CourseLogos",
                    "maincourse",
                    "menuInfo",
                    "fixedMultiplePrices",
                    "calculatedMultiplePrices",
                    "fixedprice",
                    "showFirst",
                    "deleted",
                    "enabled",
                    "menuInfoEn"
                  ],
                  "additionalProperties": false
                }
              },
              "required": [
                "id",
                "menuItemId",
                "courseId",
                "sortOrder",
                "course"
              ]
            }
          }
        },
        "required": [
          "id",
          "nameNl",
          "nameEn",
          "menuTypeId",
          "chefId",
          "enabled",
          "remark",
          "menuid",
          "sortorder",
          "menuItemContents"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "id",
    "menuDate",
    "restaurantId",
    "chefId",
    "description",
    "approvedById",
    "approvedDateTime",
    "approved",
    "requestToBeApproved",
    "remark",
    "menuItems"
  ],
  "additionalProperties": false
}

=== Ysoap/komidabot-docker/tests/external_menus/2019-11-25_cmu.raw.json
{
  "id": 242,
  "menuDate": "2019-11-25T00:00:00",
  "restaurantId": 5,
  "chefId": 0,
  "description": null,
  "approvedById": 0,
  "approvedDateTime": "0001-01-01T00:00:00",
  "approved": false,
  "requestToBeApproved": false,
  "remark": null,
  "menuItems": [
    {
      "id": 1323,
      "nameNl": null,
      "nameEn": null,
      "menuTypeId": 0,
      "chefId": 0,
      "enabled": 1,
      "remark": null,
      "menuid": 242,
      "sortorder": 0,
      "menuItemContents": [
        {
          "id": 1943,
          "menuItemId": 1323,
          "courseId": 2524,
          "sortOrder": 0,
          "course": {
            "id": 2524,
            "dispNameNl": "Bio-broccolisoep",
            "dispNameEn": "Organic broccoli soup",
            "nameNl": "bio-broccolisoep",
            "nameEn": "",
            "weight": "500ml / 700ml",
            "extra": "opwarmen in microgolf op 750 watt - roeren en genieten maar! smakelijk!",
            "preparation": null,
            "price": 0.9,
            "photo": "",
            "isCourse": false,
            "isIngredient": false,
            "course_CategoryForCourses": null,
            "course_Allergens": [],
            "course_CourseLogos": [
              {
                "courseId": 2524,
                "courseLogoId": 201
              },
              {
                "courseId": 2524,
                "courseLogoId": 211
              },
              {
                "courseId": 2524,
                "courseLogoId": 213
              }
            ],
            "maincourse": true,
            "menuInfo": null,
            "fixedMultiplePrices": false,
            "calculatedMultiplePrices": false,
            "fixedprice": true,
            "showFirst": false,
            "deleted": false,
            "enabled": true,
            "menuInfoEn": null
          }
        }
      ]
    },
    {
      "id": 1321,
      "nameNl": null,
      "nameEn": null,
      "menuTypeId": 0,
      "chefId": 0,
      "enabled": 1,
      "remark": null,
      "menuid": 242,
      "sortorder": 1,
      "menuItemContents": [
        {
          "id": 1941,
          "menuItemId": 1321,
          "courseId": 4980,
          "sortOrder": 0,
          "course": {
            "id": 4980,
            "dispNameNl": "Oosterse bulgursalade met chili",
            "dispNameEn": "Oriental bulghur salad with chilli",
            "nameNl": "00 oosterse bulgursalade met chili,w",
            "nameEn": "",
            "weight": null,
            "extra": "vegan",
            "preparation": "conceptsalade winter",
            "price": 3.8,
            "photo": "",
            "isCourse": false,
            "isIngredient": false,
            "course_CategoryForCourses": null,
            "course_Allergens": [
              {
                "courseId": 4980,
                "allergenId": 201
              },
              {
                "courseId": 4980,
                "allergenId": 205
              },
              {
                "courseId": 4980,
                "allergenId": 209
              },
              {
                "courseId": 4980,
                "allergenId": 210
              }
            ],
            "course_CourseLogos": [
              {
                "courseId": 4980,
                "courseLogoId": 209
              },
              {
                "courseId": 4980,
                "courseLogoId": 213
              }
            ],
            "maincourse": true,
            "menuInfo": null,
            "fixedMultiplePrices": true,
            "calculatedMultiplePrices": false,
            "fixedprice": false,
            "showFirst": false,
            "deleted": false,
            "enabled": true,
            "menuInfoEn": null
          }
        }
      ]
    },
    {
      "id": 1322,
      "nameNl": null,
      "nameEn": null,
      "menuTypeId": 0,
      "chefId": 0,
      "enabled": 1,
      "remark": null,
      "menuid": 242,
      "sortorder": 2,
      "menuItemContents": [
        {
          "id": 1942,
          "menuItemId": 1322,
          "courseId": 3142,
          "sortOrder": 0,
          "course": {
            "id": 3142,
            "dispNameNl": "Krokante salade",
            "dispNameEn": "Crunchy salad",
            "nameNl": "krokante salade (veggie), w",
            "nameEn": "",
            "weight": "350g",
            "extra": "koel bewaren - veggie",
            "preparation": "laagjes van onder naar boven: noten (mengeling) rammenas appel met schil (in schijfjes), besprenkelen met citroensap witloofblaren blauwe kaas veldsla croutons potje dressing",
            "price": 5.0,
            "photo": "",
            "isCourse": false,
            "isIngredient": false,
            "course_CategoryForCourses": null,
            "course_Allergens": [
              {
                "courseId": 3142,
                "allergenId": 201
              },
              {
                "courseId": 3142,
                "allergenId": 203
              },
              {
                "courseId": 3142,
                "allergenId": 204
              },
              {
                "courseId": 3142,
                "allergenId": 205
              },
              {
                "courseId": 3142,
                "allergenId": 206
              },
              {
                "courseId": 3142,
                "allergenId": 209
              }
            ],
            "course_CourseLogos": [
              {
                "courseId": 3142,
                "courseLogoId": 204
              },
              {
                "courseId": 3142,
                "courseLogoId": 209
              },
              {
                "courseId": 3142,
                "courseLogoId": 214
              }
            ],
            "maincourse": true,
            "menuInfo": null,
            "fixedMultiplePrices": true,
            "calculatedMultiplePrices": false,
            "fixedprice": false,
            "showFirst": false,
            "deleted": false,
            "enabled": true,
            "menuInfoEn": null
          }
        }
      ]
    },
    {
      "id": 1325,
      "nameNl": null,
      "nameEn": null,
      "menuTypeId": 0,
      "chefId": 0,
      "enabled": 1,
      "remark": null,
      "menuid": 242,
      "sortorder": 3,
      "menuItemContents": [
        {
          "id": 1945,
          "menuItemId": 1325,
          "courseId": 4972,
          "sortOrder": 0,
          "course": {
            "id": 4972,
            "dispNameNl": "Panini California ",
            "dispNameEn": "Panini California ",
            "nameNl": "00 california panini,w (vegan)",
            "nameEn": "",
            "weight": null,
            "extra": "vegan",
            "preparation": "snack winter olie van de tomaatjes maakt het smeuig",
            "price": 2.9,
            "photo": "",
            "isCourse": false,
            "isIngredient": false,
            "course_CategoryForCourses": null,
            "course_Allergens": [
              {
                "courseId": 4972,
                "allergenId": 201
              },
              {
                "courseId": 4972,
                "allergenId": 205
              },
              {
                "courseId": 4972,
                "allergenId": 209
              }
            ],
            "course_CourseLogos": [
              {
                "courseId": 4972,
                "courseLogoId": 210
              },
              {
                "courseId": 4972,
                "courseLogoId": 213
              }
            ],
            "maincourse": true,
            "menuInfo": null,
            "fixedMultiplePrices": false,
            "calculatedMultiplePrices": false,
            "fixedprice": true,
            "showFirst": false,
            "deleted": false,
            "enabled": true,
            "menuInfoEn": null
          }
        }
      ]
    },
    {
      "id": 1324,
      "nameNl": null,
      "nameEn": null,
      "menuTypeId": 0,
      "chefId": 0,
      "enabled": 1,
      "remark": null,
      "menuid": 242,
      "sortorder": 11,
      "menuItemContents": [
        {
          "id": 1944,
          "menuItemId": 1324,
          "courseId": 1082,
          "sortOrder": 0,
          "course": {
            "id": 1082,
            "dispNameNl": "Croque geitenkaas-honing",
            "dispNameEn": "Grilled goat cheese sandwich with honey",
            "nameNl": "croque geitenkaas-honing, dd, z & w",
            "nameEn": "",
            "weight": "200g",
            "extra": "veggie",
            "preparation": "keuze uit wit brood of bruin brood om de croque te maken 1 potje saus is in de prijs inbegrepen",
            "price": 1.6,
            "photo": "",
            "isCourse": false,
            "isIngredient": false,
            "course_CategoryForCourses": null,
            "course_Allergens": [
              {
                "courseId": 1082,
                "allergenId": 201
              },
              {
                "courseId": 1082,
                "allergenId": 203
              }
            ],
            "course_CourseLogos": [
              {
                "courseId": 1082,
                "courseLogoId": 204
              },
              {
                "courseId": 1082,
                "courseLogoId": 210
              },
              {
                "courseId": 1082,
                "courseLogoId": 214
              }
            ],
            "maincourse": true,
            "menuInfo": null,
            "fixedMultiplePrices": false,
            "calculatedMultiplePrices": false,
            "fixedprice": true,
            "showFirst": false,
            "deleted": false,
            "enabled": true,
            "menuInfoEn": null
          }
        }
      ]
    }
  ],
  "$schema": "./raw.schema.json"
}

=== Ysoap/komidabot-docker/tests/external_menus/2020-03-16_cmu.raw.json
{
  "id": 750,
  "menuDate": "2020-03-16T00:00:00",
  "restaurantId": 5,
  "chefId": 0,
  "description": null,
  "approvedById": 0,
  "approvedDateTime": "0001-01-01T00:00:00",
  "approved": false,
  "requestToBeApproved": false,
  "remark": null,
  "menuItems": [
    {
      "id": 5885,
      "nameNl": null,
      "nameEn": null,
      "menuTypeId": 0,
      "chefId": 0,
      "enabled": 1,
      "remark": null,
      "menuid": 750,
      "sortorder": 10,
      "menuItemContents": [
        {
          "id": 7960,
          "menuItemId": 5885,
          "courseId": 5685,
          "sortOrder": 0,
          "course": {
            "id": 5685,
            "dispNameNl": "Gesloten van 16/03/2020 tot en met 17/04/2020",
            "dispNameEn": "Closed from 16/03/2020 till 17/04/2020",
            "nameNl": "Gesloten van 16/03/2020 tot en met 17/04/2020 ",
            "nameEn": "",
            "weight": "",
            "extra": "",
            "preparation": "",
            "price": 0.0,
            "photo": "",
            "isCourse": true,
            "isIngredient": true,
            "course_CategoryForCourses": null,
            "course_Allergens": [],
            "course_CourseLogos": [],
            "maincourse": true,
            "menuInfo": "",
            "fixedMultiplePrices": false,
            "calculatedMultiplePrices": false,
            "fixedprice": true,
            "showFirst": false,
            "deleted": false,
            "enabled": true,
            "menuInfoEn": ""
          }
        }
      ]
    }
  ],
  "$schema": "./raw.schema.json"
}

=== Ysoap/komidabot-docker/tests/external_menus/2020-02-10_cgb.raw.json
{
  "id": 631,
  "menuDate": "2020-02-10T00:00:00",
  "restaurantId": 4,
  "chefId": 0,
  "description": null,
  "approvedById": 0,
  "approvedDateTime": "0001-01-01T00:00:00",
  "approved": false,
  "requestToBeApproved": false,
  "remark": null,
  "menuItems": [
    {
      "id": 3910,
      "nameNl": null,
      "nameEn": null,
      "menuTypeId": 0,
      "chefId": 0,
      "enabled": 1,
      "remark": null,
      "menuid": 631,
      "sortorder": 0,
      "menuItemContents": [
        {
          "id": 5440,
          "menuItemId": 3910,
          "courseId": 1605,
          "sortOrder": 0,
          "course": {
            "id": 1605,
            "dispNameNl": "Roomsoep van schorseneren",
            "dispNameEn": "Cream of salsify",
            "nameNl": "roomsoep van schorseneren",
            "nameEn": "",
            "weight": "500 ml / 700ml",
            "extra": "opwarmen in microgolf op 750 watt - roeren en genieten maar! smakelijk!",
            "preparation": null,
            "price": 0.9,
            "photo": "",
            "isCourse": false,
            "isIngredient": false,
            "course_CategoryForCourses": null,
            "course_Allergens": [
              {
                "courseId": 1605,
                "allergenId": 201
              },
              {
                "courseId": 1605,
                "allergenId": 203
              },
              {
                "courseId": 1605,
                "allergenId": 208
              }
            ],
            "course_CourseLogos": [
              {
                "courseId": 1605,
                "courseLogoId": 211
              },
              {
                "courseId": 1605,
                "courseLogoId": 214
              }
            ],
            "maincourse": true,
            "menuInfo": null,
            "fixedMultiplePrices": false,
            "calculatedMultiplePrices": false,
            "fixedprice": true,
            "showFirst": false,
            "deleted": false,
            "enabled": true,
            "menuInfoEn": null
          }
        }
      ]
    },
    {
      "id": 3911,
      "nameNl": null,
      "nameEn": null,
      "menuTypeId": 0,
      "chefId": 0,
      "enabled": 1,
      "remark": null,
      "menuid": 631,
      "sortorder": 1,
      "menuItemContents": [
        {
          "id": 5441,
          "menuItemId": 3911,
          "courseId": 4975,
          "sortOrder": 0,
          "course": {
            "id": 4975,
            "dispNameNl": "Salade Marrakech veganlicious ",
            "dispNameEn": "Marrakesh veganlicious salad ",
            "nameNl": "00 salade marrakech veganlicious(couscous,mozzarisella),dd,w (vegan)",
            "nameEn": "",
            "weight": "300 gr",
            "extra": "koel bewaren - vegan",
            "preparation": "conceptsalade winter",
            "price": 4.0,
            "photo": "",
            "isCourse": false,
            "isIngredient": false,
            "course_CategoryForCourses": null,
            "course_Allergens": [
              {
                "courseId": 4975,
                "allergenId": 201
              },
              {
                "courseId": 4975,
                "allergenId": 204
              },
              {
                "courseId": 4975,
                "allergenId": 208
              },
              {
                "courseId": 4975,
                "allergenId": 210
              }
            ],
            "course_CourseLogos": [
              {
                "courseId": 4975,
                "courseLogoId": 209
              },
              {
                "courseId": 4975,
                "courseLogoId": 213
              }
            ],
            "maincourse": true,
            "menuInfo": null,
            "fixedMultiplePrices": true,
            "calculatedMultiplePrices": false,
            "fixedprice": false,
            "showFirst": false,
            "deleted": false,
            "enabled": true,
            "menuInfoEn": null
          }
        }
      ]
    },
    {
      "id": 3916,
      "nameNl": null,
      "nameEn": null,
      "menuTypeId": 0,
      "chefId": 0,
      "enabled": 1,
      "remark": null,
      "menuid": 631,
      "sortorder": 2,
      "menuItemContents": [
        {
          "id": 5446,
          "menuItemId": 3916,
          "courseId": 3161,
          "sortOrder": 0,
          "course": {
            "id": 3161,
            "dispNameNl": "Bagel pumpkin",
            "dispNameEn": "Pumpkin bagel",
            "nameNl": "00 bagel pumpkin (cottage cheese,geroosterde pompoen), w",
            "nameEn": "",
            "weight": "250g",
            "extra": "koel bewaren - veggie",
            "preparation": "pompoen met olijfolie en pezo roosteren in de oven. bestrijk 1 kant van de bagel met de cottage cheese, beleg met de geroosterde pompoen en werk af met gecrunchte walnoten.",
            "price": 2.5,
            "photo": "",
            "isCourse": false,
            "isIngredient": false,
            "course_CategoryForCourses": null,
            "course_Allergens": [
              {
                "courseId": 3161,
                "allergenId": 200
              },
              {
                "courseId": 3161,
                "allergenId": 201
              },
              {
                "courseId": 3161,
                "allergenId": 203
              },
              {
                "courseId": 3161,
                "allergenId": 205
              },
              {
                "courseId": 3161,
                "allergenId": 208
              },
              {
                "courseId": 3161,
                "allergenId": 211
              }
            ],
            "course_CourseLogos": [
              {
                "courseId": 3161,
                "courseLogoId": 204
              },
              {
                "courseId": 3161,
                "courseLogoId": 210
              },
              {
                "courseId": 3161,
                "courseLogoId": 214
              }
            ],
            "maincourse": true,
            "menuInfo": null,
            "fixedMultiplePrices": false,
            "calculatedMultiplePrices": false,
            "fixedprice": true,
            "showFirst": false,
            "deleted": false,
            "enabled": true,
            "menuInfoEn": null
          }
        }
      ]
    },
    {
      "id": 3921,
      "nameNl": null,
      "nameEn": null,
      "menuTypeId": 0,
      "chefId": 0,
      "enabled": 1,
      "remark": null,
      "menuid": 631,
      "sortorder": 3,
      "menuItemContents": [
        {
          "id": 5451,
          "menuItemId": 3921,
          "courseId": 2424,
          "sortOrder": 0,
          "course": {
            "id": 2424,
            "dispNameNl": "Panini 'kalkoen-pesto'",
            "dispNameEn": "Turkey pesto panini",
            "nameNl": "panini 'kalkoen-pesto', z & w",
            "nameEn": "",
            "weight": "250g",
            "extra": null,
            "preparation": "vanaf nu pestospread gran'olivia gebruiken - sandwich spread opwerken",
            "price": 2.9,
            "photo": "",
            "isCourse": false,
            "isIngredient": false,
            "course_CategoryForCourses": null,
            "course_Allergens": [
              {
                "courseId": 2424,
                "allergenId": 200
              },
              {
                "courseId": 2424,
                "allergenId": 201
              },
              {
                "courseId": 2424,
                "allergenId": 203
              },
              {
                "courseId": 2424,
                "allergenId": 205
              },
              {
                "courseId": 2424,
                "allergenId": 209
              }
            ],
            "course_CourseLogos": [
              {
                "courseId": 2424,
                "courseLogoId": 202
              },
              {
                "courseId": 2424,
                "courseLogoId": 210
              }
            ],
            "maincourse": true,
            "menuInfo": null,
            "fixedMultiplePrices": false,
            "calculatedMultiplePrices": false,
            "fixedprice": true,
            "showFirst": false,
            "deleted": false,
            "enabled": true,
            "menuInfoEn": null
          }
        }
      ]
    }
  ],
  "$schema": "./raw.schema.json"
}
