=== Ysoap/komidabot-docker/tests/external_menus/raw.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "optional_string": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    }
  },
  "title": "ExternalMenu",
  "type": "object",
  "properties": {
    "$schema": true,
    "id": {
      "type": "integer"
    },
    "menuDate": {
      "type": "string",
      "format": "date-time"
    },
    "restaurantId": {
      "type": "integer"
    },
    "chefId": {
      "type": "integer",
      "minimum": 0,
      "maximum": 0
    },
    "description": {
      "type": "null"
    },
    "approvedById": {
      "type": "integer",
      "minimum": 0,
      "maximum": 0
    },
    "approvedDateTime": {
      "type": "string",
      "format": "date-time"
    },
    "approved": {
      "type": "boolean",
      "enum": [
        false
      ]
    },
    "requestToBeApproved": {
      "type": "boolean",
      "enum": [
        false
      ]
    },
    "remark": {
      "type": "null"
    },
    "menuItems": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "nameNl": {
            "type": "null"
          },
          "nameEn": {
            "type": "null"
          },
          "menuTypeId": {
            "type": "integer",
            "minimum": 0,
            "maximum": 0
          },
          "chefId": {
            "type": "integer",
            "minimum": 0,
            "maximum": 0
          },
          "enabled": {
            "type": "integer",
            "minimum": 0,
            "maximum": 2
          },
          "remark": {
            "type": "null"
          },
          "menuid": {
            "type": "integer"
          },
          "sortorder": {
            "type": "integer",
            "minimum": 0,
            "maximum": 11
          },
          "menuItemContents": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "menuItemId": {
                  "type": "integer"
                },
                "courseId": {
                  "type": "integer"
                },
                "sortOrder": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 0
                },
                "course": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "dispNameNl": {
                      "type": "string"
                    },
                    "dispNameEn": {
                      "type": "string"
                    },
                    "nameNl": {
                      "type": "string"
                    },
                    "nameEn": {
                      "type": "string"
                    },
                    "weight": {
                      "$ref": "#/definitions/optional_string"
                    },
                    "extra": {
                      "$ref": "#/definitions/optional_string"
                    },
                    "preparation": {
                      "$ref": "#/definitions/optional_string"
                    },
                    "price": {
                      "type": "number",
                      "minimum": 0.0
                    },
                    "photo": {
                      "type": "string",
                      "enum": [
                        ""
                      ]
                    },
                    "isCourse": {
                      "type": "boolean"
                    },
                    "isIngredient": {
                      "type": "boolean"
                    },
                    "course_CategoryForCourses": {
                      "type": "null"
                    },
                    "course_Allergens": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "courseId": {
                            "type": "integer"
                          },
                          "allergenId": {
                            "type": "integer"
                          }
                        },
                        "required": [
                          "courseId",
                          "allergenId"
                        ],
                        "additionalProperties": false
                      }
                    },
                    "course_CourseLogos": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "courseId": {
                            "type": "integer"
                          },
                          "courseLogoId": {
                            "type": "integer"
                          }
                        },
                        "required": [
                          "courseId",
                          "courseLogoId"
                        ],
                        "additionalProperties": false
                      }
                    },
                    "maincourse": {
                      "type": "boolean"
                    },
                    "menuInfo": {
                      "$ref": "#/definitions/optional_string"
                    },
                    "fixedMultiplePrices": {
                      "type": "boolean"
                    },
                    "calculatedMultiplePrices": {
                      "type": "boolean"
                    },
                    "fixedprice": {
                      "type": "boolean"
                    },
                    "showFirst": {
                      "type": "boolean"
                    },
                    "deleted": {
                      "type": "boolean"
                    },
                    "enabled": {
                      "type": "boolean"
                    },
                    "menuInfoEn": {
                      "$ref": "#/definitions/optional_string"
                    }
                  },
                  "required": [
                    "id",
                    "dispNameNl",
                    "dispNameEn",
                    "nameNl",
                    "nameEn",
                    "weight",
                    "extra",
                    "preparation",
                    "price",
                    "photo",
                    "isCourse",
                    "isIngredient",
                    "course_CategoryForCourses",
                    "course_Allergens",
                    "course_CourseLogos",
                    "maincourse",
                    "menuInfo",
                    "fixedMultiplePrices",
                    "calculatedMultiplePrices",
                    "fixedprice",
                    "showFirst",
                    "deleted",
                    "enabled",
                    "menuInfoEn"
                  ],
                  "additionalProperties": false
                }
              },
              "required": [
                "id",
                "menuItemId",
                "courseId",
                "sortOrder",
                "course"
              ]
            }
          }
        },
        "required": [
          "id",
          "nameNl",
          "nameEn",
          "menuTypeId",
          "chefId",
          "enabled",
          "remark",
          "menuid",
          "sortorder",
          "menuItemContents"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "id",
    "menuDate",
    "restaurantId",
    "chefId",
    "description",
    "approvedById",
    "approvedDateTime",
    "approved",
    "requestToBeApproved",
    "remark",
    "menuItems"
  ],
  "additionalProperties": false
}

=== Ysoap/komidabot-docker/tests/external_menus/2020-03-16_cde.raw.json
{
  "id": 799,
  "menuDate": "2020-03-16T00:00:00",
  "restaurantId": 2,
  "chefId": 0,
  "description": null,
  "approvedById": 0,
  "approvedDateTime": "0001-01-01T00:00:00",
  "approved": false,
  "requestToBeApproved": false,
  "remark": null,
  "menuItems": [
    {
      "id": 5834,
      "nameNl": null,
      "nameEn": null,
      "menuTypeId": 0,
      "chefId": 0,
      "enabled": 1,
      "remark": null,
      "menuid": 799,
      "sortorder": 10,
      "menuItemContents": [
        {
          "id": 7910,
          "menuItemId": 5834,
          "courseId": 5684,
          "sortOrder": 0,
          "course": {
            "id": 5684,
            "dispNameNl": "komida is minstens tot en met 3 april gesloten.",
            "dispNameEn": "From 16/03/2020 till (at least) 3/04/2020 komida will be closed.",
            "nameNl": "Vanaf 16/03/2020 tot en met 3/04/2020 is komida enkel een shop waar je terecht kan voor belegde broodjes, snoep en drank. Ter plaatse eten kan niet.",
            "nameEn": "",
            "weight": "",
            "extra": "",
            "preparation": "",
            "price": 0.0,
            "photo": "",
            "isCourse": true,
            "isIngredient": true,
            "course_CategoryForCourses": null,
            "course_Allergens": [],
            "course_CourseLogos": [],
            "maincourse": true,
            "menuInfo": "",
            "fixedMultiplePrices": false,
            "calculatedMultiplePrices": false,
            "fixedprice": true,
            "showFirst": false,
            "deleted": false,
            "enabled": true,
            "menuInfoEn": ""
          }
        }
      ]
    }
  ],
  "$schema": "./raw.schema.json"
}

=== Ysoap/komidabot-docker/tests/external_menus/2019-12-19_cgb.raw.json
{
  "id": 356,
  "menuDate": "2019-12-19T00:00:00",
  "restaurantId": 4,
  "chefId": 0,
  "description": null,
  "approvedById": 0,
  "approvedDateTime": "0001-01-01T00:00:00",
  "approved": false,
  "requestToBeApproved": false,
  "remark": null,
  "menuItems": [
    {
      "id": 2340,
      "nameNl": null,
      "nameEn": null,
      "menuTypeId": 0,
      "chefId": 0,
      "enabled": 1,
      "remark": null,
      "menuid": 356,
      "sortorder": 0,
      "menuItemContents": [
        {
          "id": 3374,
          "menuItemId": 2340,
          "courseId": 5575,
          "sortOrder": 0,
          "course": {
            "id": 5575,
            "dispNameNl": "Zilt knolseldersoepje met zeekraal",
            "dispNameEn": "silt celeriac soup with salicorn",
            "nameNl": "Zilt knolseldersoepje met zeekraal, vegan",
            "nameEn": "",
            "weight": "",
            "extra": "",
            "preparation": "Stoof de ui aan, samen met de prei en de knolselder in boter. Bevochtig daarna met de bouillon en laat zachtjes koken tot de groenten gaar zijn. Werk af met de kervel en de zeekraal.",
            "price": 0.9,
            "photo": "",
            "isCourse": true,
            "isIngredient": true,
            "course_CategoryForCourses": null,
            "course_Allergens": [
              {
                "courseId": 5575,
                "allergenId": 201
              },
              {
                "courseId": 5575,
                "allergenId": 208
              },
              {
                "courseId": 5575,
                "allergenId": 210
              }
            ],
            "course_CourseLogos": [
              {
                "courseId": 5575,
                "courseLogoId": 211
              },
              {
                "courseId": 5575,
                "courseLogoId": 213
              }
            ],
            "maincourse": true,
            "menuInfo": "",
            "fixedMultiplePrices": false,
            "calculatedMultiplePrices": false,
            "fixedprice": true,
            "showFirst": false,
            "deleted": false,
            "enabled": true,
            "menuInfoEn": null
          }
        }
      ]
    },
    {
      "id": 2431,
      "nameNl": null,
      "nameEn": null,
      "menuTypeId": 0,
      "chefId": 0,
      "enabled": 1,
      "remark": null,
      "menuid": 356,
      "sortorder": 1,
      "menuItemContents": [
        {
          "id": 3488,
          "menuItemId": 2431,
          "courseId": 5586,
          "sortOrder": 0,
          "course": {
            "id": 5586,
            "dispNameNl": "Pasta met soja-bolognaisesaus",
            "dispNameEn": "Pasta with soy bolognaise sauce",
            "nameNl": "Pasta met soja-bolognaisesaus",
            "nameEn": "",
            "weight": "",
            "extra": "",
            "preparation": "",
            "price": 3.8,
            "photo": "",
            "isCourse": true,
            "isIngredient": true,
            "course_CategoryForCourses": null,
            "course_Allergens": [
              {
                "courseId": 5586,
                "allergenId": 200
              },
              {
                "courseId": 5586,
                "allergenId": 201
              },
              {
                "courseId": 5586,
                "allergenId": 208
              },
              {
                "courseId": 5586,
                "allergenId": 210
              }
            ],
            "course_CourseLogos": [
              {
                "courseId": 5586,
                "courseLogoId": 207
              },
              {
                "courseId": 5586,
                "courseLogoId": 214
              }
            ],
            "maincourse": true,
            "menuInfo": "",
            "fixedMultiplePrices": false,
            "calculatedMultiplePrices": true,
            "fixedprice": false,
            "showFirst": false,
            "deleted": false,
            "enabled": true,
            "menuInfoEn": null
          }
        }
      ]
    },
    {
      "id": 2341,
      "nameNl": null,
      "nameEn": null,
      "menuTypeId": 0,
      "chefId": 0,
      "enabled": 1,
      "remark": null,
      "menuid": 356,
      "sortorder": 2,
      "menuItemContents": [
        {
          "id": 3375,
          "menuItemId": 2341,
          "courseId": 3141,
          "sortOrder": 0,
          "course": {
            "id": 3141,
            "dispNameNl": "Croissant met brie",
            "dispNameEn": "Croissant with brie",
            "nameNl": "croissant brie, w",
            "nameEn": "",
            "weight": "250g",
            "extra": "koel bewaren - veggie",
            "preparation": "amandelschilfers roosteren",
            "price": 2.3,
            "photo": "",
            "isCourse": false,
            "isIngredient": false,
            "course_CategoryForCourses": null,
            "course_Allergens": [
              {
                "courseId": 3141,
                "allergenId": 200
              },
              {
                "courseId": 3141,
                "allergenId": 201
              },
              {
                "courseId": 3141,
                "allergenId": 203
              },
              {
                "courseId": 3141,
                "allergenId": 205
              },
              {
                "courseId": 3141,
                "allergenId": 206
              },
              {
                "courseId": 3141,
                "allergenId": 209
              },
              {
                "courseId": 3141,
                "allergenId": 210
              }
            ],
            "course_CourseLogos": [
              {
                "courseId": 3141,
                "courseLogoId": 204
              },
              {
                "courseId": 3141,
                "courseLogoId": 210
              },
              {
                "courseId": 3141,
                "courseLogoId": 214
              }
            ],
            "maincourse": true,
            "menuInfo": null,
            "fixedMultiplePrices": false,
            "calculatedMultiplePrices": false,
            "fixedprice": true,
            "showFirst": false,
            "deleted": false,
            "enabled": true,
            "menuInfoEn": null
          }
        }
      ]
    },
    {
      "id": 2401,
      "nameNl": null,
      "nameEn": null,
      "menuTypeId": 0,
      "chefId": 0,
      "enabled": 1,
      "remark": null,
      "menuid": 356,
      "sortorder": 3,
      "menuItemContents": [
        {
          "id": 3451,
          "menuItemId": 2401,
          "courseId": 1890,
          "sortOrder": 0,
          "course": {
            "id": 1890,
            "dispNameNl": "Salade zonder sla",
            "dispNameEn": "Salad without lettuce",
            "nameNl": "salade slaatje zonder sla (aardappel, appel, raapjes), dd, w",
            "nameEn": "",
            "weight": "300g",
            "extra": "koel bewaren - veggie",
            "preparation": "scharrelei gekookt rico 75st of scharrelei gekookt rico 6x12st karton appel besprenkelen met citroensap",
            "price": 3.8,
            "photo": "",
            "isCourse": false,
            "isIngredient": false,
            "course_CategoryForCourses": null,
            "course_Allergens": [
              {
                "courseId": 1890,
                "allergenId": 200
              },
              {
                "courseId": 1890,
                "allergenId": 203
              },
              {
                "courseId": 1890,
                "allergenId": 205
              },
              {
                "courseId": 1890,
                "allergenId": 206
              },
              {
                "courseId": 1890,
                "allergenId": 208
              },
              {
                "courseId": 1890,
                "allergenId": 209
              },
              {
                "courseId": 1890,
                "allergenId": 212
              }
            ],
            "course_CourseLogos": [
              {
                "courseId": 1890,
                "courseLogoId": 209
              },
              {
                "courseId": 1890,
                "courseLogoId": 214
              }
            ],
            "maincourse": true,
            "menuInfo": null,
            "fixedMultiplePrices": false,
            "calculatedMultiplePrices": true,
            "fixedprice": false,
            "showFirst": false,
            "deleted": false,
            "enabled": true,
            "menuInfoEn": null
          }
        }
      ]
    }
  ],
  "$schema": "./raw.schema.json"
}

=== Ysoap/komidabot-docker/tests/external_menus/2020-10-26_hzs.raw.json
{
  "id": 1155,
  "menuDate": "2020-10-26T00:00:00",
  "restaurantId": 6,
  "chefId": 0,
  "description": null,
  "approvedById": 0,
  "approvedDateTime": "0001-01-01T00:00:00",
  "approved": false,
  "requestToBeApproved": false,
  "remark": null,
  "menuItems": [
    {
      "id": 9261,
      "nameNl": null,
      "nameEn": null,
      "menuTypeId": 0,
      "chefId": 0,
      "enabled": 0,
      "remark": null,
      "menuid": 1155,
      "sortorder": 10,
      "menuItemContents": []
    }
  ],
  "$schema": "./raw.schema.json"
}

=== Ysoap/komidabot-docker/tests/external_menus/2020-09-28_cmu.raw.json
{
  "id": 1027,
  "menuDate": "2020-09-28T00:00:00",
  "restaurantId": 5,
  "chefId": 0,
  "description": null,
  "approvedById": 0,
  "approvedDateTime": "0001-01-01T00:00:00",
  "approved": false,
  "requestToBeApproved": false,
  "remark": null,
  "menuItems": [
    {
      "id": 8040,
      "nameNl": null,
      "nameEn": null,
      "menuTypeId": 0,
      "chefId": 0,
      "enabled": 1,
      "remark": null,
      "menuid": 1027,
      "sortorder": 0,
      "menuItemContents": [
        {
          "id": 10294,
          "menuItemId": 8040,
          "courseId": 5820,
          "sortOrder": 0,
          "course": {
            "id": 5820,
            "dispNameNl": "komida@Mutsaard is voorlopig gesloten",
            "dispNameEn": "",
            "nameNl": "komida@Mutsaard is temporarily closed",
            "nameEn": "",
            "weight": "",
            "extra": "",
            "preparation": "",
            "price": 0.0,
            "photo": "",
            "isCourse": true,
            "isIngredient": true,
            "course_CategoryForCourses": null,
            "course_Allergens": [],
            "course_CourseLogos": [],
            "maincourse": true,
            "menuInfo": "",
            "fixedMultiplePrices": false,
            "calculatedMultiplePrices": false,
            "fixedprice": false,
            "showFirst": false,
            "deleted": false,
            "enabled": true,
            "menuInfoEn": ""
          }
        }
      ]
    }
  ],
  "$schema": "./raw.schema.json"
}

=== Ysoap/komidabot-docker/tests/external_menus/2020-09-28_hzs.raw.json
{
  "id": 1022,
  "menuDate": "2020-09-28T00:00:00",
  "restaurantId": 6,
  "chefId": 0,
  "description": null,
  "approvedById": 0,
  "approvedDateTime": "0001-01-01T00:00:00",
  "approved": false,
  "requestToBeApproved": false,
  "remark": null,
  "menuItems": [
    {
      "id": 8035,
      "nameNl": null,
      "nameEn": null,
      "menuTypeId": 0,
      "chefId": 0,
      "enabled": 1,
      "remark": null,
      "menuid": 1022,
      "sortorder": 0,
      "menuItemContents": [
        {
          "id": 10288,
          "menuItemId": 8035,
          "courseId": 5829,
          "sortOrder": 0,
          "course": {
            "id": 5829,
            "dispNameNl": "komida@Hogere Zeevaartschool is momenteel enkel het ophaalpunt voor de online bestellingen: https://nl-20202040ra.iziii.pro/",
            "dispNameEn": "komida@Hogere Zeevaarschool functions as our pick up point for online orders: https://nl-20202040ra.iziii.pro/",
            "nameNl": "komida@Hogere Zeevaartschool is momenteel enkel het ophaalpunt voor de online bestellingen: https://nl-20202040ra.iziii.pro/",
            "nameEn": "",
            "weight": "",
            "extra": "",
            "preparation": "",
            "price": 0.0,
            "photo": "",
            "isCourse": true,
            "isIngredient": true,
            "course_CategoryForCourses": null,
            "course_Allergens": [],
            "course_CourseLogos": [],
            "maincourse": true,
            "menuInfo": "",
            "fixedMultiplePrices": false,
            "calculatedMultiplePrices": false,
            "fixedprice": false,
            "showFirst": false,
            "deleted": false,
            "enabled": true,
            "menuInfoEn": ""
          }
        }
      ]
    }
  ],
  "$schema": "./raw.schema.json"
}
